---
- hosts: localhost
  connection: local
  become: true # enable root

  tasks:
  - name: install packages
    package:
      name:
        - chromium-browser
        - fzf
        - gdb
        - git
        - htop
        - python3
        - terminator
        - tmux
        - tree
        - unzip
        - valgrind
        - vim
        - zsh
