---
- hosts: localhost
  connection: local
  become: false

  pre_tasks:
  - name: update repositories
    apt: update_cache=yes
    changed_when: false
    become: true

  - name: home directory creation
    become: no
    file:
      path: "~"
      state: directory
      mode: 0751

  tasks:
  - name: Upgrading all packages (Ubuntu/Debian)
    become: true
    apt:
      upgrade: dist

  - name: install packages
    become: true
    package:
      name:
        - bat
        - chromium-browser
        - cargo
        - curl
        - dconf-cli
        - delta
        - fail2ban
        - fd-find
        - fzf
        - gdb
        - git
        - htop
        - iptables
        - iptables-persistent
        - make
        - moreutils
        - netfilter-persistent
        - openssh-server
        - python3
        - ruby-dev
        - sudo
        - terminator
        - tmux
        - tree
        - unattended-upgrades
        - unzip
        - valgrind
        - vim-nox
        - wget
        - zsh
      state: latest

  - name: Remove third parties packages
    become: true
    apt:
      pkg: unity-webapps-common
      state: absent

  - name: Remove firefox
    become: true
    snap:
      name: firefox
      state: absent

  - name: Installl exa
    become: no
    shell:
      cmd: cargo install exa
      creates: "~/.cargo/bin/exa"

  - include_tasks: tasks/users.yml

  - include_tasks: tasks/install_zsh.yml

  - include_tasks: tasks/change_shell.yml

  - include_tasks: tasks/vim.yml

  - include_tasks: tasks/generate_ssh_keys.yml

  - include_tasks: tasks/sshd.yml

  - include_tasks: tasks/iptables.yml

  - include_tasks: tasks/fail2ban.yml

  - include_tasks: tasks/unattended-upgrades.yml

  - include_tasks: tasks/dconf.yml

  - include_tasks: tasks/ansible-cron.yml
