---
- hosts: localhost
  connection: local
  become: false 

  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
  - name: install packages
    become: true
    package:
      name:
        - bat
        - chromium-browser
        - cargo
        - curl
        - delta
        - fd-find
        - fzf
        - gdb
        - git
        - htop
        - moreutils
        - openssh-server
        - python3
        - terminator
        - tmux
        - tree
        - unzip
        - valgrind
        - vim
        - wget
        - zsh

  - name: Remove third parties packages
    become: true
    apt:
      pkg: unity-webapps-common
      state: absent

  - name: Remove firefox
    become: true
    snap:
      name: firefox
      state: absent

  - name: Installl exa 
    become: no
    shell:
      cmd: cargo install exa 
      creates: "~/.cargo/bin/exa"

  - include_tasks: tasks/install_zsh.yml
    tags:
      - shell

  - include_tasks: tasks/change_shell.yml
    tags:
      - shell

  - include_tasks: tasks/dconf.yml

  - include_tasks: tasks/ansible-cron.yml
