---
- hosts: localhost
  connection: local
  become: true # enable root

  tasks:
  - name: install packages
    package:
      name:
        - chromium-browser
        - fzf
        - gdb
        - git
        - htop
        - python3
        - terminator
        - tmux
        - tree
        - unzip
        - valgrind
        - vim
        - wget
        - zsh

  - name: copy .bashrc file
    copy:
      src: files/bashrc
      dest: /home/{{user}}/.bashrc
      group: '{{user}}'
      owner: '{{user}}'
