---
- hosts: localhost
  connection: local
  become: false 

  tasks:
  - name: install packages
    become: true
    package:
      name:
        - chromium-browser
        - curl
        - fzf
        - gdb
        - git
        - htop
        - python3
        - terminator
        - tmux
        - tree
        - unzip
        - valgrind
        - vim
        - wget
        - zsh

  - name: Remove third parties packages
    become: true
    apt:
      pkg: unity-webapps-common
      state: absent

  - include_tasks: tasks/install_zsh.yml
    tags:
      - shell

  - include_tasks: tasks/change_shell.yml
    tags:
      - shell

  - include_tasks: tasks/dconf.yml

  - include_tasks: tasks/ansible-cron.yml
