---
   - name: Create log directory
     file:
       path: ~/log
       state: directory

   - name: add ansible-pull cron job
     become: true
     cron:
       name: ansible auto-provision
       user: "ansible"
       minute: "*/10"
       job: sudo -i -u {{ansible_user_id}} bash -c 'tail -n 1000 ~/log/ansible-cron | sponge ~/log/ansible-cron; ansible-pull -o -vvv -U https://github.com/laurent-xu/bootstrap.git | ts "[\%Y-\%m-\%d \%H:\%M:\%S]" >> ~/log/ansible-cron 2>&1'
