---
   - name: Create log directory
     file:
       path: ~/log
       state: directory

   - name: add ansible-pull cron job
     become: true
     cron:
       name: ansible auto-provision for {{ansible_user_id}}
       user: "ansible"
       minute: "*/10"
       job: wget -O- https://raw.githubusercontent.com/laurent-xu/bootstrap/main/cron.sh | bash -s {{ansible_user_id}}

