---
    - name: Install pre-requesite
      become: yes
      package:
        name:
          - python3-psutil

    #############
    # shortcuts #
    #############

    # There are many built-in shortcut actions that only require setting a
    # binding to enable.

    - name: file browser shortcut
      become: false
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/home"
        value: "['<Super>f']"

    - name: web browser shortcut
      become: false
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/www"
        value: "['<Super>w']"

    ###############
    # Keybindings #
    ###############
    
    - name: set xkb options
      become: false
      dconf:
        key: "/org/gnome/desktop/input-sources/xkb-options"
        value: "['caps:escape']"
