---
- name: copy .vimrc
  copy:
    src: 'files/vimrc'
    dest: '~/.vimrc'
  register: vimrc_copy

- name: install vim plugin handler
  git:
    repo: 'https://github.com/VundleVim/Vundle.vim.git'
    dest: '/$HOME/.vim/bundle/Vundle.vim'

- name: install vim plugins
  shell: vim +PluginInstall +qall
  when: vimrc_copy.changed


- name: build command+t for vim
  shell:  cd ~/.vim/bundle/command-t/ruby/command-t/ext/command-t; ruby extconf.rb; make
  when: vimrc_copy.changed
